#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Script generated by Vivado on Fri Apr 17 11:51:26 KST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : robot_arm.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : robot_arm.sh
#                robot_arm.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                robot_arm.sh [-reset_run]
#                robot_arm.sh [-reset_log]
#                robot_arm.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'robot_arm.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip lib_cdc_v1_0_3 proc_sys_reset_v5_0_16 xil_defaultlib axi_lite_ipif_v3_0_4 lib_pkg_v1_0_4 lib_srl_fifo_v1_0_4 axi_uartlite_v2_0_37 microblaze_v11_0_14 microblaze_riscv_v1_0_3 lmb_v10_v3_0_14 lmb_bram_if_cntlr_v4_0_25 blk_mem_gen_v8_4_9 mdm_riscv_v1_0_3 xlconstant_v1_1_9 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_33 axi_vip_v1_1_19 interrupt_control_v3_1_5 axi_gpio_v2_0_35)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "robot_arm.sh - Script generated by export_simulation (Vivado v2024.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./robot_arm.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vhdlan -work lib_cdc_v1_0_3 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_16 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_proc_sys_reset_0_0/sim/robot_arm_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_clk_wiz_0/robot_arm_clk_wiz_0_clk_wiz.v" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_clk_wiz_0/robot_arm_clk_wiz_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_pkg_v1_0_4 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_srl_fifo_v1_0_4 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_uartlite_v2_0_37 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/9a87/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_uartlite_0_0/sim/robot_arm_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work microblaze_v11_0_14 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/a243/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work microblaze_riscv_v1_0_3 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f9dd/hdl/microblaze_riscv_v1_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_microblaze_riscv_0_0/sim/robot_arm_microblaze_riscv_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lmb_v10_v3_0_14 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/7495/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_dlmb_v10_0/sim/robot_arm_dlmb_v10_0.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_ilmb_v10_0/sim/robot_arm_ilmb_v10_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lmb_bram_if_cntlr_v4_0_25 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/73e9/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_dlmb_bram_if_cntlr_0/sim/robot_arm_dlmb_bram_if_cntlr_0.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_ilmb_bram_if_cntlr_0/sim/robot_arm_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work blk_mem_gen_v8_4_9 $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/5ec1/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_lmb_bram_0/sim/robot_arm_lmb_bram_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work mdm_riscv_v1_0_3 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/d547/hdl/mdm_riscv_v1_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_mdm_1_0/sim/robot_arm_mdm_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/sim/bd_c18a.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconstant_v1_1_9 $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_0/sim/bd_c18a_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_1/sim/bd_c18a_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_2/sim/bd_c18a_arinsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_3/sim/bd_c18a_rinsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_4/sim/bd_c18a_awinsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_5/sim/bd_c18a_winsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_6/sim/bd_c18a_binsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_7/sim/bd_c18a_aroutsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_8/sim/bd_c18a_routsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_9/sim/bd_c18a_awoutsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_10/sim/bd_c18a_woutsw_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_11/sim/bd_c18a_boutsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_12/sim/bd_c18a_arni_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_13/sim/bd_c18a_rni_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_14/sim/bd_c18a_awni_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_15/sim/bd_c18a_wni_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_16/sim/bd_c18a_bni_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f49a/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_17/sim/bd_c18a_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_18/sim/bd_c18a_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/63ed/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_19/sim/bd_c18a_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_20/sim/bd_c18a_s00a2s_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_21/sim/bd_c18a_sarn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_22/sim/bd_c18a_srn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_23/sim/bd_c18a_sawn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_24/sim/bd_c18a_swn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_25/sim/bd_c18a_sbn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_26/sim/bd_c18a_m00s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_27/sim/bd_c18a_m00arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_28/sim/bd_c18a_m00rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_29/sim/bd_c18a_m00awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_30/sim/bd_c18a_m00wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_31/sim/bd_c18a_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/37bc/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_32/sim/bd_c18a_m00e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_33/sim/bd_c18a_m01s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_34/sim/bd_c18a_m01arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_35/sim/bd_c18a_m01rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_36/sim/bd_c18a_m01awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_37/sim/bd_c18a_m01wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_38/sim/bd_c18a_m01bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_39/sim/bd_c18a_m01e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_40/sim/bd_c18a_m02s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_41/sim/bd_c18a_m02arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_42/sim/bd_c18a_m02rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_43/sim/bd_c18a_m02awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_44/sim/bd_c18a_m02wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_45/sim/bd_c18a_m02bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_46/sim/bd_c18a_m02e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_47/sim/bd_c18a_m03s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_48/sim/bd_c18a_m03arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_49/sim/bd_c18a_m03rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_50/sim/bd_c18a_m03awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_51/sim/bd_c18a_m03wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_52/sim/bd_c18a_m03bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_53/sim/bd_c18a_m03e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_54/sim/bd_c18a_m04s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_55/sim/bd_c18a_m04arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_56/sim/bd_c18a_m04rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_57/sim/bd_c18a_m04awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_58/sim/bd_c18a_m04wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_59/sim/bd_c18a_m04bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_60/sim/bd_c18a_m04e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_61/sim/bd_c18a_m05s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_62/sim/bd_c18a_m05arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_63/sim/bd_c18a_m05rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_64/sim/bd_c18a_m05awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_65/sim/bd_c18a_m05wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_66/sim/bd_c18a_m05bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_67/sim/bd_c18a_m05e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_68/sim/bd_c18a_m06s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_69/sim/bd_c18a_m06arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_70/sim/bd_c18a_m06rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_71/sim/bd_c18a_m06awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_72/sim/bd_c18a_m06wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_73/sim/bd_c18a_m06bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_74/sim/bd_c18a_m06e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_75/sim/bd_c18a_m07s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_76/sim/bd_c18a_m07arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_77/sim/bd_c18a_m07rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_78/sim/bd_c18a_m07awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_79/sim/bd_c18a_m07wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_80/sim/bd_c18a_m07bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_81/sim/bd_c18a_m07e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_82/sim/bd_c18a_m08s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_83/sim/bd_c18a_m08arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_84/sim/bd_c18a_m08rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_85/sim/bd_c18a_m08awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_86/sim/bd_c18a_m08wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_87/sim/bd_c18a_m08bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_88/sim/bd_c18a_m08e_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_89/sim/bd_c18a_m09s2a_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_90/sim/bd_c18a_m09arn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_91/sim/bd_c18a_m09rn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_92/sim/bd_c18a_m09awn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_93/sim/bd_c18a_m09wn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_94/sim/bd_c18a_m09bn_0.sv" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/bd_0/ip/ip_95/sim/bd_c18a_m09e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_register_slice_v2_1_33 $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_vip_v1_1_19 $vlogan_opts -sverilog +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_smc_0/sim/robot_arm_axi_smc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work interrupt_control_v3_1_5 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_gpio_v2_0_35 $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/6718/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_0_0/sim/robot_arm_axi_gpio_0_0.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_1_0/sim/robot_arm_axi_gpio_1_0.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_2_0/sim/robot_arm_axi_gpio_2_0.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_3_0/sim/robot_arm_axi_gpio_3_0.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_4_0/sim/robot_arm_axi_gpio_4_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_servo_pwm_4ch_0_0/sim/robot_arm_servo_pwm_4ch_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_5_0/sim/robot_arm_axi_gpio_5_0.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_5_1/sim/robot_arm_axi_gpio_5_1.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_5_2/sim/robot_arm_axi_gpio_5_2.vhd" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/ip/robot_arm_axi_gpio_5_3/sim/robot_arm_axi_gpio_5_3.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/3cbc" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/f0b6/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/0127/hdl/verilog" +incdir+"../../../../robot_arm.gen/sources_1/bd/robot_arm/ipshared/ec67/hdl" +incdir+"/opt/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../robot_arm.gen/sources_1/bd/robot_arm/sim/robot_arm.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.robot_arm xil_defaultlib.glbl -o robot_arm_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./robot_arm_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/user1/workspace_ondevice_2/SoC/robot_arm/robot_arm.cache/compile_simlib/vcs"
  fi

  echo "LIBRARY_SCAN=TRUE" >> $file

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key robot_arm_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc robot_arm_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./robot_arm.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: robot_arm.sh [-help]\n\
Usage: robot_arm.sh [-step]\n\
Usage: robot_arm.sh [-lib_map_path]\n\
Usage: robot_arm.sh [-reset_run]\n\
Usage: robot_arm.sh [-reset_log]\n\
Usage: robot_arm.sh [-keep_index]\n\
Usage: robot_arm.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
